DROP TABLE IF EXISTS base;
CREATE TABLE base(
	UNIQUE_ID INTEGER GENERATED ALWAYS AS IDENTITY, 
	t TIMESTAMP,
	tex VARCHAR(1000) NOT NULL
	);
	
CREATE TABLE WORDS (
	TIME TIMESTAMP,
	WORD VARCHAR(1000)
	);
CREATE TABLE PHRASES (
	TIME TIMESTAMP,
	PHRASE VARCHAR(1000)
	);
CREATE TABLE FINAL (
	TIME TIMESTAMP,
	UNIQUE_WORD VARCHAR(1000),
	FREQUENCY INTEGER
	);

