DROP TABLE IF EXISTS base;
CREATE TABLE base(
	t VARCHAR(1000),
	tex VARCHAR(1000) NOT NULL
	);
DROP TABLE IF EXISTS WORDS;
CREATE TABLE WORDS (
	TIME TIMESTAMP,
	WORD VARCHAR(1000)
	);
DROP TABLE IF EXISTS PHRASES;
CREATE TABLE PHRASES (
	TIME TIMESTAMP,
	PHRASE VARCHAR(1000)
	);
DROP TABLE IF EXISTS FINAL;
CREATE TABLE FINAL (
	TIME TIMESTAMP,
	UNIQUE_WORD VARCHAR(1000),
	FREQUENCY INTEGER
	);
